"""empty message

Revision ID: abf517546384
Revises: ef2c80f3d89b
Create Date: 2022-11-04 10:42:41.670399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abf517546384'
down_revision = 'ef2c80f3d89b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('make', sa.String(length=100), nullable=False))
    op.add_column('car', sa.Column('model', sa.String(length=100), nullable=False))
    op.add_column('car', sa.Column('color', sa.String(length=100), nullable=True))
    op.add_column('car', sa.Column('year', sa.String(length=4), nullable=True))
    op.drop_column('car', 'address')
    op.drop_column('car', 'email')
    op.drop_column('car', 'phone_number')
    op.drop_column('car', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('car', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('car', sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('car', sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('car', 'year')
    op.drop_column('car', 'color')
    op.drop_column('car', 'model')
    op.drop_column('car', 'make')
    # ### end Alembic commands ###
